CREATE TABLE Customer_Behaviour(
Customer_ID SERIAL PRIMARY KEY,
Age	INT,
Gender VARCHAR(50),
Item_Purchased VARCHAR(50),
Category VARCHAR(50),
Purchase_Amount_USD DECIMAL (10,2),	
Location VARCHAR(100),
Size VARCHAR(10),
Color VARCHAR(50),
Season VARCHAR(50),
Review_Rating DECIMAL(2,1),
Subscription_Status VARCHAR(10),
Shipping_Type VARCHAR(100),
Discount_Applied VARCHAR(10),
Promo_Code_Used VARCHAR(10),
Previous_Purchases INT,	
Payment_Method VARCHAR(50),
Frequency_of_Purchases VARCHAR(50)
);

SELECT * FROM Customer_Behaviour;

COPY
Customer_Behaviour(Customer_ID,	Age, Gender,Item_Purchased,	Category,Purchase_Amount_USD,Location,Size,
Color,Season,Review_Rating,Subscription_Status,
Shipping_Type,Discount_Applied,Promo_Code_Used,Previous_Purchases,Payment_Method,Frequency_of_Purchases
)
FROM 'C:\Temp\customer_shopping_behavior.csv'
DELIMITER ','
CSV HEADER;

DROP TABLE IF EXISTS Customer_Behaviour;


--Q1. What is the total revenue generated by male vs. female customers?
select gender, 
SUM(Purchase_Amount_USD) as revenue
from Customer_Behaviour
group by gender;


--Q2. Which customers used a discount but still spent more than the average purchase amount? 
select Customer_ID, Purchase_Amount_USD 
from Customer_Behaviour
where Discount_Applied = 'Yes' and Purchase_Amount_USD >= (select AVG(Purchase_Amount_USD) 
from Customer_Behaviour);


-- Q3. Which are the top 5 products with the highest average review rating?
select Item_Purchased,
round(avg(Review_Rating::numeric),2) as "Average_Product_Rating"
from Customer_Behaviour
group by Item_Purchased
order by avg(Review_Rating) desc
limit 5;

SELECT * FROM Customer_Behaviour;

--Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 
select shipping_type, 
ROUND(AVG(Purchase_Amount_USD),2)
from Customer_Behaviour
where shipping_type in ('Standard','Express')
group by shipping_type;

SELECT * FROM Customer_Behaviour;

--Q5. Do subscribed customers spend more? Compare average spend and total revenue 
--between subscribers and non-subscribers.
SELECT Subscription_Status,
       COUNT(Customer_ID) AS total_customers,
       ROUND(AVG(Purchase_Amount_USD),2) AS avg_spend,
       ROUND(SUM(Purchase_Amount_USD),2) AS total_revenue
FROM Customer_Behaviour
GROUP BY Subscription_Status
ORDER BY total_revenue,avg_spend DESC;

--Q6. Which 5 products have the highest percentage of purchases with discounts applied?
SELECT Item_Purchased,
       ROUND(100.0 * SUM(CASE WHEN Discount_Applied = 'Yes' THEN 1 ELSE 0 END)/COUNT(*),2) AS discount_rate
FROM Customer_Behaviour
GROUP BY Item_Purchased
ORDER BY Discount_Rate DESC
LIMIT 5;


--Q7. Segment customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment. 
with Customer_Type as (
SELECT Customer_ID, Previous_Purchases,
CASE 
    WHEN Previous_Purchases = 1 THEN 'New'
    WHEN Previous_Purchases BETWEEN 2 AND 10 THEN 'Returning'
    ELSE 'Loyal'
    END AS customer_segment
FROM Customer_Behaviour)
select customer_segment,count(*) AS "Number of Customers" 
from customer_type 
group by customer_segment;

--Q8. What are the top 3 most purchased products within each category? 
WITH item_counts AS (
    SELECT category,
           item_purchased,
           COUNT(customer_id) AS total_orders,
           ROW_NUMBER() OVER (PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS item_rank
    FROM Customer_Behaviour
    GROUP BY category, item_purchased
)
SELECT item_rank,category, item_purchased, total_orders
FROM item_counts
WHERE item_rank <=3;
 
--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT subscription_status,
       COUNT(customer_id) AS repeat_buyers
FROM Customer_Behaviour
WHERE previous_purchases > 5
GROUP BY subscription_status;

--Q10. What is the revenue contribution of each age group? 
SELECT Age,
    SUM(Purchase_Amount_USD) AS total_revenue
FROM Customer_Behaviour
GROUP BY Age
ORDER BY total_revenue desc;

